version: "3"
services:
  api:
    image: registration-api:latest
    container_name: api
    environment: 
      PORT: ${PORT}
      HOST: ${HOST}
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db: 
    image: postgres
    container_name: postgresdb
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

